# -*- coding: utf-8 -*-
"""protocol_counter.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJoPpMnKcRXUsz5CDJdmz2Xrut88kSIS
"""

!pip install scapy

from google.colab import files

uploaded = files.upload()

from scapy.all import rdpcap

packets = rdpcap("day2_capture.pcapng")

print("Total Packets:", len(packets))

from collections import Counter

protocols = Counter()

for pkt in packets:
    protocols[pkt.__class__.__name__] += 1

print(protocols)

from scapy.all import *
from collections import Counter

packets = rdpcap("day2_capture.pcapng")

protocol_counter = Counter()

for pkt in packets:

    if pkt.haslayer("TCP"):
        protocol_counter["TCP"] += 1

    elif pkt.haslayer("UDP"):
        protocol_counter["UDP"] += 1

    elif pkt.haslayer("ICMP"):
        protocol_counter["ICMP"] += 1

print("Protocol Statistics")
print(protocol_counter)

from scapy.all import *
from collections import Counter

packets = rdpcap("day2_capture.pcapng")

ips = []

for pkt in packets:
    if IP in pkt:
        ips.append(pkt[IP].src)
        ips.append(pkt[IP].dst)

counter = Counter(ips)

print(counter.most_common(10))

!pip install matplotlib

import matplotlib.pyplot as plt

protocols = {
    "TCP": 1250,
    "UDP": 430,
    "ICMP": 12
}

plt.figure(figsize=(8,5))
plt.bar(protocols.keys(), protocols.values())

plt.title("Protocol Distribution")
plt.xlabel("Protocol")
plt.ylabel("Packet Count")

plt.show()

import matplotlib.pyplot as plt

top_ips = dict(counter.most_common(10))

plt.figure(figsize=(10,5))

plt.bar(top_ips.keys(), top_ips.values())

plt.title("Top Communicating Hosts")
plt.xlabel("IP Address")
plt.ylabel("Packet Count")

plt.xticks(rotation=45)

plt.show()

